### ISSUE TITLE
Lookup headers case-insensitively

### ISSUE THREAD

**Issue by RumataEstor** [nico-amsterdam/pop3mail#3]
It seems that the headers must be looked up case insensitively: 
> https://tools.ietf.org/html/rfc5322#section-1.2.2
> a case-insensitive literal value enclosed in quotation marks

However when the headers are parsed (in `epop_message:parse_header/1`), they are provided as is without any sort of normalisation, and the lookup functionality also doesn't apply any normalisation.

Is normalisation absence intended, or is it desired but missing functionality?

**Comment by nico-amsterdam** [comment]
You are right, the header lookup should be case-insensitive.

**Comment by nico-amsterdam** [comment]
This is resolved now.

Elixir users do this:
   mix deps.clean erlpop
   mix deps.update erlpop

I published erlpop also on hex.pm as pop3client. To use hex package:
Elixir, in mix.exs add deps:     {:erlpop, "~> 1.2" , hex: "pop3client"}
Erlang, in rebar.config add deps: {erlpop, "1.2.0", {pkg, pop3client}}
